import type { NextPage } from "next";
import Head from "next/head";
import AboutProducts from "../sections/AboutProducts/AboutProducts";
import FeaturedIn from "../sections/FeaturedIn/FeaturedIn";
import FeatureProducts from "../sections/FeatureProducts/FeatureProducts";
import Hero from "../sections/Hero/Hero";
import PopularArticles from "../sections/PopularArticles/PopularArticles";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gym Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedIn />
      <AboutProducts />
      <FeatureProducts />
      <PopularArticles />
    </div>
  );
};

export default Home;
